export const TOKEN_TYPE_PASSWORD_RESET = 'PASSWORD_RESET' as const;
export const TOKEN_TYPE_EMAIL_VERIFICATION = 'EMAIL_VERIFICATION' as const;

export type TokenType =
    | typeof TOKEN_TYPE_PASSWORD_RESET
    | typeof TOKEN_TYPE_EMAIL_VERIFICATION;
